
PUT localhost:9200/_opendistro/_ism/policies/age
Content-Type: application/json

{
  "policy": {
    "description": "ingesting logs",
    "default_state": "ingest",
    "states": [
      {
        "name": "ingest",
        "actions": [],
        "transitions": [
          {
            "state_name": "search",
            "conditions": {
              "min_index_age": "30m"
            }
          }
        ]
      },
      {
        "name": "search",
        "actions": [],
        "transitions": [
        ]
      }
    ]
  }
}

###

PUT localhost:9200/_opendistro/_ism/policies/docs
Content-Type: application/json

{
  "policy": {
    "description": "ingesting logs",
    "default_state": "ingest",
    "states": [
      {
        "name": "ingest",
        "actions": [
        ],
        "transitions": [
          {
            "state_name": "search",
            "conditions": {
              "min_doc_count": "10"
            }
          }
        ]
      },
      {
        "name": "search",
        "actions": [],
        "transitions": [
        ]
      }
    ]
  }
}

###

PUT localhost:9200/_opendistro/_ism/policies/size
Content-Type: application/json

{
  "policy": {
    "description": "ingesting logs",
    "default_state": "ingest",
    "states": [
      {
        "name": "ingest",
        "actions": [
        ],
        "transitions": [
          {
            "state_name": "search",
            "conditions": {
              "min_size": "30kb"
            }
          }
        ]
      },
      {
        "name": "search",
        "actions": [],
        "transitions": [
        ]
      }
    ]
  }
}

###

PUT localhost:9200/_opendistro/_ism/policies/cron
Content-Type: application/json

{
  "policy": {
    "description": "ingesting logs",
    "default_state": "ingest",
    "states": [
      {
        "name": "ingest",
        "actions": [

        ],
        "transitions": [
          {
            "state_name": "search",
            "conditions": {
              "cron": {
                "cron": {
                  "expression": "* 17 * * * *"
                }
              }
            }
          }
        ]
      },
      {
        "name": "search",
        "actions": [],
        "transitions": [
        ]
      }
    ]
  }
}